### ISSUE TITLE
Incorrect subfolder reference /lib/

### ISSUE THREAD

**Issue by rtek1000** [ryanplusplus/sdcc-stm8-tools#1]
> $ make -f target.mk
> lib/stm8-tiny/lib_stm8-tiny.mk:3: lib/stm8-tiny/lib/tiny/lib_tiny.mk: No such file or directory
> make: *** No rule to make target 'lib/stm8-tiny/lib/tiny/lib_tiny.mk'.  Stop.

Locale: https://github.com/ryanplusplus/sdcc-stm8-tools/tree/edc824fbd1116014c436104e6041bf87078bdabb/lib

Solved:

From: https://github.com/ryanplusplus/stm8s-header/tree/6877c77d9e1da88f27c155f48a9997c9062b127f

To: https://github.com/ryanplusplus/stm8-tiny/tree/75fb9a4b18cc0510bd41f386d83fc1fe53b3997b

**Comment by ryanplusplus** [comment]
Hey @rtek1000 ! I'm glad to see someone is using this!

Can you clarify what the issue is? I see your error above, but to me that looks like you might not have all of the submodules. Can you try running `git submodule update --init --recursive` to initialize and update all of the submodules and then try again?

**Comment by rtek1000** [comment]
$ git clone --recursive https://github.com/ryanplusplus/w1209
Cloning into 'w1209'...
remote: Enumerating objects: 179, done.
remote: Counting objects: 100% (179/179), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 179 (delta 79), reused 142 (delta 44), pack-reused 0
Receiving objects: 100% (179/179), 26.09 KiB | 329.00 KiB/s, done.
Resolving deltas: 100% (79/79), done.
Submodule 'lib/stm8-tiny' (https://github.com/ryanplusplus/stm8-tiny) registered for path 'lib/stm8-tiny'
Submodule 'tools' (https://github.com/ryanplusplus/sdcc-stm8-tools) registered for path 'tools'
Cloning into '/W1209/ryanplusplus/w1209/lib/stm8-tiny'...
remote: Enumerating objects: 319, done.        
remote: Counting objects: 100% (25/25), done.        
remote: Compressing objects: 100% (17/17), done.        
remote: Total 319 (delta 11), reused 14 (delta 3), pack-reused 294        
Receiving objects: 100% (319/319), 44.21 KiB | 276.00 KiB/s, done.
Resolving deltas: 100% (185/185), done.
Cloning into '/W1209/ryanplusplus/w1209/tools'...
remote: Enumerating objects: 7143, done.        
remote: Counting objects: 100% (484/484), done.        
remote: Compressing objects: 100% (453/453), done.        
remote: Total 7143 (delta 79), reused 173 (delta 27), pack-reused 6659        
Receiving objects: 100% (7143/7143), 166.06 MiB | 230.00 KiB/s, done.
Resolving deltas: 100% (4947/4947), done.
Submodule path 'lib/stm8-tiny': checked out 'b6ec56b272f8d7d7d9cc95abc9dcd531250328c8'
fatal: detected dubious ownership in repository at '/W1209/ryanplusplus/w1209/lib/stm8-tiny'
To add an exception for this directory, call:

	git config --global --add safe.directory /W1209/ryanplusplus/w1209/lib/stm8-tiny
Submodule path 'tools': checked out 'edc824fbd1116014c436104e6041bf87078bdabb'
fatal: detected dubious ownership in repository at '/W1209/ryanplusplus/w1209/tools'
To add an exception for this directory, call:

	git config --global --add safe.directory /W1209/ryanplusplus/w1209/tools
fatal: Failed to recurse into submodule path 'lib/stm8-tiny'
fatal: Failed to recurse into submodule path 'tools'

**Comment by rtek1000** [comment]
> $ make -f target.mk
> Compiling tiny_comm.c.rel...
> Compiling tiny_crc16.c.rel...
> Compiling tiny_event.c.rel...
> Compiling tiny_event_queue.c.rel...
> Compiling tiny_event_subscription.c.rel...
> Compiling tiny_fsm.c.rel...
> Compiling tiny_hsm.c.rel...
> Compiling tiny_list.c.rel...
> Compiling tiny_message_bus.c.rel...
> Compiling tiny_ram_key_value_store.c.rel...
> Compiling tiny_ring_buffer.c.rel...
> Compiling tiny_single_subscriber_event.c.rel...
> Compiling tiny_stack_allocator.c.rel...
> Compiling tiny_timer.c.rel...
> Building tiny.lib...

> $ make -f target.mk upload
> Compiling data_model.c.rel...
> Compiling display.c.rel...
> Compiling keypad.c.rel...
> src/device/keypad.c:66: error 78: incompatible types
> from type 'void function ( struct tiny_timer_group_t generic* auto, void generic* auto) fixed'
>   to type 'void function ( void generic* fixed) code* fixed'
> make: *** [/W1209/ryanplusplus/w1209/tools/sdcc.mk:179: build/src/device/keypad.c.rel] Error 1

**Comment by ryanplusplus** [comment]
Thanks for the extra info. Here's what I get when I clone:

```
$ git clone --recursive https://github.com/ryanplusplus/w1209
Cloning into 'w1209'...
remote: Enumerating objects: 179, done.
remote: Counting objects: 100% (179/179), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 179 (delta 79), reused 142 (delta 44), pack-reused 0
Receiving objects: 100% (179/179), 26.09 KiB | 685.00 KiB/s, done.
Resolving deltas: 100% (79/79), done.
Submodule 'lib/stm8-tiny' (https://github.com/ryanplusplus/stm8-tiny) registered for path 'lib/stm8-tiny'
Submodule 'tools' (https://github.com/ryanplusplus/sdcc-stm8-tools) registered for path 'tools'
Cloning into '/home/ryan/Downloads/w1209/lib/stm8-tiny'...
remote: Enumerating objects: 319, done.        
remote: Counting objects: 100% (25/25), done.        
remote: Compressing objects: 100% (17/17), done.        
remote: Total 319 (delta 11), reused 14 (delta 3), pack-reused 294        
Receiving objects: 100% (319/319), 44.21 KiB | 2.01 MiB/s, done.
Resolving deltas: 100% (185/185), done.
Cloning into '/home/ryan/Downloads/w1209/tools'...
remote: Enumerating objects: 7143, done.        
remote: Counting objects: 100% (484/484), done.        
remote: Compressing objects: 100% (453/453), done.        
remote: Total 7143 (delta 79), reused 173 (delta 27), pack-reused 6659        
Receiving objects: 100% (7143/7143), 166.06 MiB | 16.84 MiB/s, done.
Resolving deltas: 100% (4947/4947), done.
Submodule path 'lib/stm8-tiny': checked out 'b6ec56b272f8d7d7d9cc95abc9dcd531250328c8'
Submodule 'lib/tiny' (https://github.com/ryanplusplus/tiny) registered for path 'lib/stm8-tiny/lib/tiny'
Cloning into '/home/ryan/Downloads/w1209/lib/stm8-tiny/lib/tiny'...
remote: Enumerating objects: 895, done.        
remote: Counting objects: 100% (334/334), done.        
remote: Compressing objects: 100% (178/178), done.        
remote: Total 895 (delta 220), reused 206 (delta 141), pack-reused 561        
Receiving objects: 100% (895/895), 153.92 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (570/570), done.
Submodule path 'lib/stm8-tiny/lib/tiny': checked out 'b5ac7363ee47d40186be92a184abc05f4c06e2a2'
Submodule path 'tools': checked out 'edc824fbd1116014c436104e6041bf87078bdabb'
Submodule 'lib/stm8' (https://github.com/ryanplusplus/stm8s-header) registered for path 'tools/lib/stm8'
Submodule 'utils' (https://github.com/ryanplusplus/build-tools-utils) registered for path 'tools/utils'
Cloning into '/home/ryan/Downloads/w1209/tools/lib/stm8'...
remote: Enumerating objects: 61, done.        
remote: Total 61 (delta 0), reused 0 (delta 0), pack-reused 61        
Receiving objects: 100% (61/61), 82.34 KiB | 714.00 KiB/s, done.
Resolving deltas: 100% (28/28), done.
Cloning into '/home/ryan/Downloads/w1209/tools/utils'...
remote: Enumerating objects: 25, done.        
remote: Counting objects: 100% (25/25), done.        
remote: Compressing objects: 100% (18/18), done.        
remote: Total 25 (delta 13), reused 14 (delta 6), pack-reused 0        
Receiving objects: 100% (25/25), done.
Resolving deltas: 100% (13/13), done.
Submodule path 'tools/lib/stm8': checked out '6877c77d9e1da88f27c155f48a9997c9062b127f'
Submodule path 'tools/utils': checked out 'b6cb720b7b0ffe9c74ebf2d2cb07e0a308807a4b'
```

It's able to get all submodules without a problem. I've never seen the dubious ownership warning before so I'm not sure how to solve that without adding a safe directory.

I'm able to reproduce the build issue you shared:

```
$ make -f target.mk upload
Compiling data_model.c.rel...
Compiling display.c.rel...
Compiling keypad.c.rel...
Compiling relay.c.rel...
Compiling tim4_system_tick.c.rel...
Compiling test.c.rel...
Compiling tiny_comm.c.rel...
Compiling tiny_crc16.c.rel...
src/device/keypad.c:66: error 78: incompatible types
from type 'void function ( struct tiny_timer_group_t generic* auto, void generic* auto) fixed'
  to type 'void function ( void generic* fixed) code* fixed'
make: *** [/home/ryan/Downloads/w1209/tools/sdcc.mk:179: build/src/device/keypad.c.rel] Error 1
make: *** Waiting for unfinished jobs....
```

I'll get this fixed as soon as I can.

**Comment by ryanplusplus** [comment]
[This commit](https://github.com/ryanplusplus/w1209/commit/cf5bc94b7f9ba3feaf3a1bac6483a2b010bb28f9) should solve the build failure. Thanks for the heads up!
